preprocess:
  dropoff_datetime: False
transform:
  normalise: True
dataset:
 test_size: 0.1
 random_state: 42
model:
  sample: True
  sample_size: 5000
  add_info: "noramlised"
  try_model: True
  tune_gradient_boosting: False
  tune_random_forest: False
  tune_XGBoost: False
  tune_light_boost: False