preprocess:
  sample: True
  sample_size: 20000
  dropoff_datetime: False
transform:
  normalise: False
dataset:
 test_size: 0.1
 random_state: 42
model:
  add_info: ""
  try_model: True
  tune_gradient_boosting: False
  tune_random_forest: False
  tune_XGBoost: False
  tune_light_boost: False