name: CI CD pipeline

on:
    push

jobs:
    build:
        runs-on: hyp_tunning

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup_cml
              uses: iterative/setup-cml@v1

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.12

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Configure Aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Download Dataset from S3
              run: |
               mkdir -p ./data/raw
               mkdir -p ./model
               aws s3 cp s3://nyc-taxi/dataset.csv ./data/raw/
            
            - name: running pipeline
              run: dvc exp run

            - name: creating report
              env:
                REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: |
                python ./src/generate_report.py
                cml comment create report.md
            
            - name: copying files
              run: |
               cp ./data/interim/ppl.pkl ./data/ppl.pkl
               cp ./data/interim/fn_y.pkl ./data/fn_y.pkl

            - name: uploading data
              uses: actions/upload-artifact@v4
              with:
                name: models
                path: ./model/*